In [36]:
import re, time, requests, json
import numpy as np
import pandas as pd
from tqdm import tqdm

with open('C:/Users/twentystones/Desktop/사회연결망분석텀프로젝트/영석 수정중/KnuSentiLex-master/KnuSentiLex/data/SentiWord_info.json', encoding='utf-8-sig', mode='r') as f:
    data = json.load(f)

dict_knu = pd.DataFrame(data)
dict_knu

         word word_root polarity
0         (-;         (        1
1       (;_;)     (;_;)       -1
2        (^^)      (^^)        1
3       (^-^)     (^-^)        1
4        (^^*         (        1
...       ...       ...      ...
14838  반신반의하다      반신반의        0
14839    신비롭다        신비        1
14840   아리송하다       아리송       -1
14841    알쏭하다       알쏭하       -1
14842  알쏭달쏭하다      알쏭달쏭       -1

[14843 rows x 3 columns]

In [34]:
blog = pd.read_csv('C:/Users/twentystones/Desktop/사회연결망분석텀프로젝트/blog_crawling.csv', encoding='utf-8-sig', header=None)
blog.rename(columns= {0:'title', 1:'URL', 2:'day', 3:'body'}, inplace=True)
blog

,title,URL,day,body
0,청담 파인다이닝 도쿄등심에서 이렇게 한우를 드세요,https://blog.naver.com/vivakoreaa?Redirect=Log...,3일 전,청담 파인다이닝 도쿄등심에서 이렇게 한우를 드세요도쿄등심 청담점에 다녀왔습니다.누네...
1,도쿄네일살롱 덕천동 네일에서 겨울 맞이 엘사 그라데이션,https://blog.naver.com/lala1010?Redirect=Log&l...,어제,날씨도 추워졌겠다 오랜만에 너덜너덜해진 열손가락의 꽃단장을 위하여 덕천동 네일로 향...
2,도쿄쇼핑여행. 롤렉스와 에르메스는 신주쿠(新宿)에 다...,https://blog.naver.com/shoudai?Redirect=Log&lo...,5시간 전,"안녕하세요, 도쿄드라이브입니다. 최근 롤렉스나 에르메스의 인기모델들은 정식매장에 가..."
3,[도쿄워홀] D+335 / 여유로운 야스미 / 키치죠지...,https://blog.naver.com/k_maengsoon?Redirect=Lo...,2시간 전,2021.11.17 아침 사진이 하나뚜 없ㄴㅔ건강보험 뭐 우편 온거 땜에 일어나서 ...
4,『광교 소고기 맛집』도쿄등심 광교점-디너 스페셜 A코스 2인,https://blog.naver.com/kazuyyy?Redirect=Log&lo...,2일 전,곧 다가올 와이프님과의 5주년 결혼기념일.​포근한 주말을 맞이하여 분당에서 광교앨리...
5,"[도쿄 워홀]D+300 와 300일! 탈리즈 오픈, 우에노, 고흐전 관람",https://blog.naver.com/dlawlals87?Redirect=Log...,어제,와 나 300일이나 여기에 살았네..3일째랑 30일째 되는 날엔 뭘 했지...?기억...
6,선릉역 소고기 맛집 도쿄등심선릉점,https://blog.naver.com/0610_cth?Redirect=Log&l...,3일 전,선릉역 소고기 맛집 도쿄등심선릉점 와이프와 함께 코엑스 전시보고 맛있는 소고기 먹으...
7,[숙대맛집] 작은도쿄 일본식 튀김덮밥 텐동 존맛탱!!,https://blog.naver.com/5jinhwa?Redirect=Log&lo...,3일 전,"작은도쿄평일 11:30~21:00브레이크타임 15:00~17:00토일,공휴일 휴무숙..."
8,도곡동 맛집 분위기 끝판왕 도쿄등심 도곡점,https://blog.naver.com/jjjadeland?Redirect=Log...,2021.10.26.,도곡동 맛집 분위기 끝판왕 도쿄등심 도곡점​​​ ​​* 안녕하세요 제이드입니다. ...
9,여의도 데이트 유럽풍 감성 도쿄등심 한우 코스요리,https://blog.naver.com/sunna434?Redirect=Log&l...,22시간 전,여의도는 수많은 빌딩들이 밀집되어 있어화려한 건축물의 조명등으로 야경이 아름다운 ...
10,"도쿄등심 여의도점 - 분위기 좋은 여의도 데이트 맛집, 기념일...",https://blog.naver.com/envely11?Redirect=Log&l...,5일 전,"도쿄등심 여의도점 - 분위기 좋은 여의도 데이트 맛집, 기념일 맛집으로 추천해!​안..."
11,[도쿄워홀] D+326 디즈니랜드,https://blog.naver.com/dbqls1997?Redirect=Log&...,1시간 전,​오늘은 히나랑 디~즈니란도 가는 날 ~JR 시계 여기는 스페이드모양이다 귀여워마이...
12,【도쿄 힐링여행】 도쿄의 단풍명소,https://blog.naver.com/gotokyo-kr?Redirect=Log...,6일 전,도쿄에서는 단풍이 절정을 맞이하고 있어요!오늘은 추천 단풍명소를 소개해 드릴게요. ...
13,일본생활//도쿄생활....2021년 11월의 기록...그 첫번째...,https://blog.naver.com/mskim0910?Redirect=Log&...,7일 전,2021년 11월의 기록...PART 1이제 슬슬 노랑 노랑해지기 시작한.....도...
14,도쿄쇼핑여행. 시계쇼핑하기 좋은 긴자(銀座). 와코에서 만난...,https://blog.naver.com/shoudai?Redirect=Log&lo...,5일 전,"안녕하세요, 도쿄드라이브입니다. 긴자(銀座)는 쇼핑하기 참좋은 도쿄의 유명 관광스팟..."
15,도쿄 리벤저스 만화 원화전 공식 개최 결정 비주얼 공개,https://blog.naver.com/ptj0969?Redirect=Log&lo...,어제,"도쿄 리벤저스 만화 원화전 , 오사카서 내년 열려 티저 비주얼 공개와쿠이 켄 도쿄..."
16,"[도쿄워홀 329日] 알바, 스시로, 필카 현상 결과물 ㅎ…",https://blog.naver.com/seol_4813?Redirect=Log&...,어제,"2021.11.16 (화) 329일차​​​​6:30-11 도토루하 데마에칸 진짜,,..."
17,북경어언대학교 도쿄분교 8가지 매력,https://blog.naver.com/u_hakseang?Redirect=Log...,2일 전,​ 일본유학 중국유학북경어언대학교 도쿄분교​ ​​중국의 북경어언대학교는1962년 중...
18,"[도쿄 워홀]D+295 황금빛 가을, 카와구치코 feat.자전차왕...",https://blog.naver.com/dlawlals87?Redirect=Log...,6일 전,오늘은 충동질로 버스표 끊은 카와구치코 가는 날^^일기예보도 안보고 아 갈까? 가야...
19,매봉역 맛집 청사과 소르베 도쿄등심 도곡점,https://blog.naver.com/jjy790888?Redirect=Log&...,어제,디너코스 B 으로 먹었어요남편과 저 둘이서 간만에 데이트 하는느낌으로 먹었는데 분위...
20,"광교 소고기 도쿄등심 - 앨리웨이 맛집, 원천호수 맛집",https://blog.naver.com/dondogi?Redirect=Log&lo...,6일 전,광교에 간 김에 점심을 먹으러 앨리웨이(Alleyway)에 갔다. < 광교 앨리웨이...
21,[랜선 타고 일본여행] 도쿄... (カレッタ汐留 展望台)【도쿄】,https://blog.naver.com/nanzzang00?Redirect=Log...,어제,"smartparty.jp곤니치와 ~^^""일본여행 크리에이터 난짱이야.​​먼저 매번 ..."
22,11월14일 ( 도쿄 맑음 ) 도쿄 근교 유원지 요미우리랜드...,https://blog.naver.com/fashionkim76?Redirect=L...,3일 전,오늘은 👶 기다리는 요미우리랜드 ( 🎡 유원지 ) 遊園地よみうりランド遊園地よみうりラ...
23,"무오키 at 청담 (+롤린우드, 도쿄스위츠)",https://blog.naver.com/lyceenne?Redirect=Log&l...,2021.11.02.,아 얘들아 내가 아직 얘길 안했지 아이폰13 샀다고...(출시때 직구함)(미니 스타...
24,"도쿄일상 | 기무라타쿠야 생일파티, 에비스, 시부야 죠시카이",https://blog.naver.com/bazi1?Redirect=Log&logN...,어제,남친보다 친구만나는날에 더 머리랑 화장을 공들여한다...왜냐..사진 오조억장 찍거든...
25,도쿄맛집여행. 오모테산도의 분위기있는 야키니쿠 레스토랑...,https://blog.naver.com/shoudai?Redirect=Log&lo...,2일 전,"안녕하세요, 도쿄드라이브입니다. 이번 포스팅은 도쿄의 트렌디한 고급동네 오모테산도(..."
26,【도쿄 숙박시설】 객실이 예술 작품으로 된 '파크 호텔 도쿄',https://blog.naver.com/gotokyo-kr?Redirect=Log...,2일 전,아트를 좋아하시는 분이 놓치면 후회할 호텔을 소개해 드릴게요! ​ 도쿄·신바시에...
27,도쿄쇼핑여행. 오모테산도 힐즈 근처 이시다(ISHIDA)워치에서...,https://blog.naver.com/shoudai?Redirect=Log&lo...,어제,"안녕하세요, 도쿄드라이브입니다. 일본 도쿄에서 쇼핑하기 좋은 동네는 몇군데 있는데요..."
28,"[도쿄 워홀]D+301 또 우에노공원, 도쿄 구석구석 산책하기",https://blog.naver.com/dlawlals87?Redirect=Log...,4시간 전,오늘은 탈리즈 7-10시프트!끝나고 뭐할까 고민하다가이제 있을 시간도 얼마 안남았으...
29,위드코로나 시대의 도쿄 긴자식스(GSIX)와 스타벅스 리저브,https://blog.naver.com/shoudai?Redirect=Log&lo...,2021.10.31.,"안녕하세요, 도쿄드라이브입니다. 최근 도쿄는 긴급사태선언(緊急事態宣言)이 끝나고, ..."

In [42]:
start = time.time()

score_list = []

#score_sum, score_two, score_one, score_zero, score_mone, score_mtwo = [], [], [], [], [], []

for i in range(len(blog['body'])):
    
    score_sum, score_two, score_one, score_zero, score_mone, score_mtwo = 0, 0, 0, 0, 0, 0
    
    for j in tqdm(range(len(blog['body'][i].split(' ')))):
    
        for k in range(0, len(dict_knu)):

            if dict_knu['word'][k] == blog['body'][i].split(' ')[j]:
                
                score_sum += int(dict_knu['polarity'][k])
                
                if int(dict_knu['polarity'][k]) == 2:
                    score_two += 1
                    
                elif int(dict_knu['polarity'][k]) == 1:
                    score_one += 1
                    
                elif int(dict_knu['polarity'][k]) == 0:
                    score_zero += 1
                    
                elif int(dict_knu['polarity'][k]) == -1:
                    score_mone += 1
                    
                else:
                    score_mtwo += 1
                
    score_list.append([score_sum, score_two, score_one, score_zero, score_mone, score_mtwo])

print(f"{time.time() - start:.0f} s")

100%|████████████████████████████████████████████████████████████████████████████████| 409/409 [05:12<00:00,  1.31it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 685/685 [13:19<00:00,  1.17s/it]
100%|████████████████████████████████████████████████████████████████████████████████| 777/777 [16:01<00:00,  1.24s/it]
100%|████████████████████████████████████████████████████████████████████████████████| 609/609 [09:47<00:00,  1.04it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 349/349 [03:31<00:00,  1.65it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 395/395 [04:21<00:00,  1.51it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 487/487 [06:31<00:00,  1.25it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 200/200 [01:33<00:00,  2.14it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 516/516 [06:42<00:00,  1.28it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 834/834 [14:07<00:00,  1.02s/it]
100%|████████████████████████████████████████████████████████████████████████████████| 606/606 [07:40<00:00,  1.32it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 556/556 [06:35<00:00,  1.41it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 384/384 [03:16<00:00,  1.96it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 278/278 [02:06<00:00,  2.19it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 819/819 [13:26<00:00,  1.01it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 200/200 [01:17<00:00,  2.59it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 252/252 [01:55<00:00,  2.19it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 236/236 [01:51<00:00,  2.11it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 359/359 [03:36<00:00,  1.66it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 1138/1138 [28:03<00:00,  1.48s/it]
100%|████████████████████████████████████████████████████████████████████████████████| 970/970 [19:51<00:00,  1.23s/it]
100%|████████████████████████████████████████████████████████████████████████████████| 440/440 [04:47<00:00,  1.53it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.47it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 255/255 [01:52<00:00,  2.26it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 312/312 [02:43<00:00,  1.91it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 628/628 [09:08<00:00,  1.15it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 224/224 [01:36<00:00,  2.33it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 1172/1172 [28:11<00:00,  1.44s/it]
100%|████████████████████████████████████████████████████████████████████████████████| 168/168 [00:55<00:00,  3.02it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 497/497 [06:00<00:00,  1.38it/s]

13565 s

In [43]:
data = pd.DataFrame({'score_sum':score_list})
data

                score_sum
0     [10, 3, 7, 0, 1, 1]
1     [-1, 5, 4, 1, 5, 5]
2     [12, 7, 6, 0, 0, 4]
3      [1, 6, 1, 0, 6, 3]
4     [13, 5, 5, 0, 2, 0]
5      [1, 2, 2, 0, 3, 1]
6   [42, 16, 10, 0, 0, 0]
7      [2, 1, 1, 0, 1, 0]
8    [25, 9, 13, 0, 4, 1]
9   [58, 23, 19, 0, 5, 1]
10   [38, 8, 23, 0, 1, 0]
11     [9, 6, 1, 5, 2, 1]
12    [23, 9, 5, 0, 0, 0]
13    [-1, 2, 0, 0, 1, 2]
14   [15, 3, 16, 0, 1, 3]
15    [-2, 0, 1, 0, 1, 1]
16    [-1, 0, 1, 0, 0, 1]
17     [3, 1, 1, 2, 0, 0]
18     [7, 3, 3, 0, 2, 0]
19  [49, 20, 16, 0, 5, 1]
20   [35, 9, 20, 2, 3, 0]
21     [9, 8, 3, 0, 2, 4]
22     [0, 0, 0, 0, 0, 0]
23    [12, 5, 2, 0, 0, 0]
24     [5, 0, 6, 0, 1, 0]
25    [20, 8, 7, 0, 1, 1]
26     [4, 1, 2, 0, 0, 0]
27  [37, 15, 16, 0, 3, 3]
28     [9, 5, 0, 0, 1, 0]
29   [28, 9, 11, 0, 1, 0]

In [58]:
pd.concat([blog, data],axis=1).to_csv('도쿄결과.csv', encoding='utf-8-sig')